# Generated by Django 5.0 on 2024-05-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(default='kb8jogflltpvlfu', max_length=15, unique=True),
        ),
    ]
