# Generated by Django 5.0 on 2024-05-04 19:29

from django.db import migrations
import random
import string

def generate_id_number():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=15))

def add_id_number_field(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    for customer in CustomUser.objects.all():
        customer.id_number = generate_id_number()
        customer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_id_number'),
    ]

    operations = [
        migrations.RunPython(add_id_number_field),
    ]
