# Generated by Django 5.0 on 2024-05-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_created_by_alter_customuser_id_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_by',
        ),
        migrations.AddField(
            model_name='customuser',
            name='attachement',
            field=models.CharField(default='e310-8f32-425b', max_length=15),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(default='c3ogu59auu6vd3k', max_length=15, unique=True),
        ),
    ]
