# Generated by Django 5.0 on 2024-05-05 01:56

from django.db import migrations

def add_id_number_field(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    for customer in CustomUser.objects.all():
        customer.attachement = "e310-8f32-425b"
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_created_by_customuser_attachement_and_more'),
    ]

    operations = [
        migrations.RunPython(add_id_number_field),
    ]
