# Generated by Django 5.0 on 2024-05-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240505_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(default='6h6ttd213cj9tur', max_length=15, unique=True),
        ),
    ]
