# Generated by Django 5.0 on 2024-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(default='ds2okwehgqf9p9n', max_length=15, unique=True),
        ),
    ]
