# Generated by Django 5.0 on 2024-05-05 23:42

from django.db import migrations

def add_user_type_field(apps, schema_editor):
    CustomUser = apps.get_model('accounts', 'CustomUser')
    for customer in CustomUser.objects.all():
        customer.user_type = "collaborator"
        customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_id_number'),
    ]

    operations = [
        migrations.RunPython(add_user_type_field),
    ]
