# Generated by Django 5.0 on 2024-05-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_customuser_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(default='gbybdwowr0p2668', max_length=15, unique=True),
        ),
    ]
