# Generated by Django 5.0 on 2024-05-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_customuser_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
