# Generated by Django 5.0 on 2024-05-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(default='Kinshasa', max_length=100),
        ),
    ]
