# Generated by Django 5.0 on 2024-05-04 19:30

from django.db import migrations
import random
import string

def generate_id_number():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=15))

def add_company_id_number_field(apps, schema_editor):
    CompanyModel = apps.get_model('company', 'Company')
    for company in CompanyModel.objects.all():
        company.id_number = generate_id_number()
        company.save()

def add_customer_id_number_field(apps, schema_editor):
    CustomerModel = apps.get_model('company', 'Customer')
    for customer in CustomerModel.objects.all():
        customer.id_number = generate_id_number()
        customer.save()

def add_invoice_id_number_field(apps, schema_editor):
    InvoiceModel = apps.get_model('company', 'Invoice')
    for invoice in InvoiceModel.objects.all():
        invoice.id_number = generate_id_number()
        invoice.save()

def add_article_id_number_field(apps, schema_editor):
    ArticleModel = apps.get_model('company', 'Article')
    for article in ArticleModel.objects.all():
        article.id_number = generate_id_number()
        article.save()

class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_article_id_number_alter_company_id_number_and_more'),
    ]

    operations = [
        migrations.RunPython(add_company_id_number_field),
        migrations.RunPython(add_customer_id_number_field),
        migrations.RunPython(add_invoice_id_number_field),
        migrations.RunPython(add_article_id_number_field),
    ]
