# Generated by Django 5.0 on 2024-05-04 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20240504_2130'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(related_name='related_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='id_number',
            field=models.CharField(default='joq7ctlmhf8wjr4', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id_number',
            field=models.CharField(default='zpl9sa98uw7pjm7', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='save_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='created_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(default='2atcltg0qwh6let', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='save_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id_number',
            field=models.CharField(default='spyzt8hxlhziw4l', max_length=15, unique=True),
        ),
    ]
