# Generated by Django 5.0 on 2024-05-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_users_alter_article_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id_number',
            field=models.CharField(default='hqgl4gyt4icfq21', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id_number',
            field=models.CharField(default='xp7xr1jgkbgx8k6', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(default='gn3t1zb4v0npg1l', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id_number',
            field=models.CharField(default='iaymem0ryi9vtxa', max_length=15, unique=True),
        ),
    ]
