# Generated by Django 5.0 on 2024-05-06 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_article_id_number_alter_company_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(default='Kinshasa', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='id_number',
            field=models.CharField(default='bhklvydh6u85w3k', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id_number',
            field=models.CharField(default='68d19jiheml2ls9', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(default='tt76ky8c5z8yf4e', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id_number',
            field=models.CharField(default='xmvnvxvpf9sy6lu', max_length=15, unique=True),
        ),
    ]
