# Generated by Django 5.0 on 2024-05-10 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_customer_state_alter_article_id_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id_number',
            field=models.CharField(default='28xbkzvoz0hmkov', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='company.invoice'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id_number',
            field=models.CharField(default='j5puz3d7qjabjbb', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(default='fvh34jdypkj7x6c', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id_number',
            field=models.CharField(default='rdavskcrwju66v7', max_length=15, unique=True),
        ),
    ]
