# Generated by Django 5.0 on 2024-05-10 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_article_id_number_alter_article_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id_number',
            field=models.CharField(default='vwnfa23tdby1vy4', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id_number',
            field=models.CharField(default='2oggfy8zy6uzvne', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='save_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(default='frfilbuvqnp47uo', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id_number',
            field=models.CharField(default='5bz2aopcq2wvjh5', max_length=15, unique=True),
        ),
    ]
