# Generated by Django 5.0 on 2024-05-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_article_id_number_alter_company_id_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='type',
        ),
        migrations.AlterField(
            model_name='article',
            name='id_number',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(default='', editable=False, max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='id_number',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
